<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Validator;

class Lang extends Authenticatable
{
    public function getAll()
    {
        $english = [

        'rating'                                => 'Califícanos, ¿cómo estuvo la comida? ',
        'location_title'                        => 'Tu ubicación',
        'location_change'                       => 'Cambio',
        'store_trending'                        => 'Tendencias',
        'store_close'                           => 'La tienda está cerrada ahora.',
        'home_title'                            => 'Inicio',
        'search_title'                          => 'Buscar',
        'profile_title'                         => 'Perfil',
        'setting_title'                         => 'Configuración de cuenta',
        'user_name'                             => 'Nombre completo',
        'user_email'                            => 'Email',
        'username_msg'                          => 'este correo electrónico será tu nombre de usuario',
        'user_phone'                            => 'Teléfono',
        'user_password'                         => 'Cambia tu contraseña',
        'user_button'                           => 'Actualizar',
        'logout'                                => 'Cerrar sesión',
        'profile_welcome'                       => 'Bienvenidos',
        'order_history'                         => 'Historial de pedidos',
        'profile_infomation'                    => 'Información del perfil',
        'item_title'                            => 'Articulo',
        'item_price'                            => 'Precio',
        'item_qty'                              => 'Cantidad',
        'item_total'                            => 'Total',
        'item_status'                           => 'Estus',
        'item_cancel'                           => 'Cancelar',
        'item_empty'                            => 'Opps! Aún no tienes ningún pedido.',
        'account_update'                        => 'Actualizar configuración de cuenta',
        'success_line'                          => 'Su pedido realizado con éxito. ID de pedido es',
        'success_notify'                        => 'Se le notificará cuando cambie el estado del pedido',
        'success_home'                          => 'Volver a inicio',
        'checkout_welcome'                      => 'Revise su dirección de entrega antes de realizar el pedido',
        'checkout_title'                        => 'Checkout',
        'checkout_del'                          => 'Dirección de entrega',
        'checkout_notes'                        => 'Cualquier instrucción especial',
        'place_order'                           => 'Realizar pedido',
        'signup_account'                        => 'Ya tienes una cuenta?',
        'signup'                                => 'Regístrate',
        'choose_password'                       => 'Elegir una contraseña',
        'signup_welcome'                        => 'Crea tu cuenta para hacer un pedido rápido',
        'signup_title'                          => 'Regístrate',
        'fb'                                    => 'Iniciar sesión con Facebook',
        'or'                                    => 'o',
        'login_account'                         => "No tengo una cuenta?",
        'login_signup'                          => 'Regístrate ahora',
        'login_password'                        => 'Contraseña',
        'login_username'                        => 'Nombre de usuario/Email',
        'login_welcome'                         => 'Iniciar sesión',
        'login_title'                           => 'Iniciar sesión',
        'offer_title'                           => 'Aplicar código de cupón',
        'offer_apply'                           => 'Aplica ya',
        'cart_payable_amount'                   => 'Cantidad a pagar',
        'cart_apply_code'                       => 'Aplicar código de cupón',
        'cart_change_code'                      => 'Cambiar código de cupón',
        'cart_d_charges'                        => 'Los gastos de envío',
        'cart_discount'                         => 'Descuento',
        'cart_total'                            => 'Cantidad total',
        'cart_title'                            => 'Ver carrito',
        'search_title'                          => 'Buscar',
        'search_text'                           => 'Buscar',
        'search_hint'                           => 'Comienza a escribir...',
        'search_new'                            => 'Recién abierta',
        'search_trend'                          => 'Tendencias',
        'search_discount'                       => 'Descuento',
        'checkout_delivery'                     => 'Entrega a domicilio',
        'checkout_pickup'                       => 'Recoger',
        'chat_title'                            => 'Chat',
        'chat_text'                             => '¿Tienes algún problema? no te preocupes, dinos que te ayudaremos.',
        'chat_message'                          => 'Escribe tu mensaje',
        'chat_success'                          => '¡Gracias! Hemos recibido tu mensaje.',
        'chat_error'                            => 'Actualice su correo electrónico para enviarnos un mensaje.',




        ];

       $arabic = [

        'rating'                                => 'Rate us, how was the food ',
        'location_title'                        => 'المدينه',
        'location_change'                       => 'تغيير المدينه',
        'store_trending'                        => 'الاكثر شيوعا',
        'store_close'                           => 'المطعم مغلق الان',
        'home_title'                            => 'الرئيسيه',
        'search_title'                          => 'بحث',
        'profile_title'                         => 'الملف الشخصي',
        'setting_title'                         => 'ضبط الحساب',
        'user_name'                             => 'الاسم كامل',
        'user_email'                            => 'البريد الالكتروني',
        'username_msg'                          => 'الايميل سيكون اسم المستخدم',
        'user_phone'                            => 'الهاتف',
        'user_password'                         => 'تغيير كلمة السر',
        'user_button'                           => 'تحديث',
        'logout'                                => 'تسجيل خروج',
        'profile_welcome'                       => 'اهلا وسهلا',
        'order_history'                         => 'الطلبات السابقه',
        'profile_infomation'                    => 'معلومات المستخدم',
        'item_title'                            => 'المنتج',
        'item_price'                            => 'السعر',
        'item_qty'                              => 'الكميه',
        'item_total'                            => 'المجموع',
        'item_status'                           => 'الحاله',
        'item_cancel'                           => 'الغاء',
        'item_empty'                            => 'اسف, لا يوجد اي طلبات سابقه',
        'account_update'                        => 'تحديث الحساب',
        'success_line'                          => 'طلبك اضيفه بنجاح, رقم الطلب ',
        'success_notify'                        => 'سيتم اعلامكم بحال تغير حالة الطلب ',
        'success_home'                          => 'الردوع للرئيسيه',
        'checkout_welcome'                      => 'الرجاء مراجعة عنوان التوصيل قبل اكمل العمليه',
        'checkout_title'                        => 'Checkout',
        'checkout_del'                          => 'عنوان التوصيل',
        'place_order'                           => 'اضف طلب',
        'signup_account'                        => 'عندك حساب؟',
        'signup'                                => 'تسجيل حساب',
        'choose_password'                       => 'إختر كلمة مرور',
        'signup_welcome'                        => '!انشىء حساب الان لطب اسرع',
        'signup_title'                          => 'تسجيل حساب جديد',
        'fb'                                    => 'سجل دخول باستخدام الفيسبوك',
        'or'                                    => 'أو',
        'login_account'                         => "ليس لك معنا حساب؟",
        'login_signup'                          => '!سجل معنا الان',
        'login_password'                        => 'كلمة المرور',
        'login_username'                        => 'اسم المستخدم او البريد الالكتروني',
        'login_welcome'                         => 'الرجاء تسجيل الدخول ',
        'login_title'                           => 'تسجيل دخول',
        'offer_title'                           => 'اضف قسيمة تسوق',
        'offer_apply'                           => 'تطبيق الان',
        'cart_payable_amount'                   => 'المبلغ المتحق للدفع',
        'cart_apply_code'                       => 'تطبيق قسيمه تسوق',
        'cart_change_code'                      => 'تغيير قسيمة تسوق',
        'cart_d_charges'                        => 'تكلفة التوصيل',
        'cart_discount'                         => 'خصم',
        'cart_total'                            => 'مجموع الحساب',
        'cart_title'                            => 'اظهر السله',
        'search_title'                          => 'Search',
        'search_text'                           => 'Search for restaurants, dishes',
        'search_hint'                           => 'Start typing...',
        'search_new'                            => 'Newly Opened',
        'search_trend'                          => 'Trending',
        'search_discount'                       => 'Discount',
        'checkout_notes'                        => 'Any Special instruction',
        'checkout_delivery'                     => 'Home Delivery',
        'checkout_pickup'                       => 'Pickup',
        'chat_title'                            => 'Chat',
        'chat_text'                             => 'Having any problem? do not worry, let us know we will help you.',
        'chat_message'                          => 'Write Your Message',
        'chat_success'                          => 'Thank You! we have received your message.',
        'chat_error'                            => 'Please update your email for send us a message',





        ];

        return ['english' => $english,'arabic' => $arabic];
    }
}
